### ISSUE TITLE
是否有意向与Zotero Better Notes共同开发

### ISSUE THREAD

**Issue by windingwind** [018/zotcard#11]
您好，

我是[Zotero Better Notes](https://github.com/windingwind/zotero-better-notes)插件作者winding。有用户向我推荐了您的插件，并希望能够与Better Notes进行集成，对Better Notes中的子笔记实现卡片展示功能。请问您是否有兴趣协助/共同开发这部分？

我注意到zotcard与Better Notes一样具有模板功能，也许可以在zotcard中引入Better Notes的模板编辑器（尽管目前还是非常粗糙的编辑器）。我也愿意协助您维护zotcard。

祝好！

**Comment by 018** [comment]
您好，感谢邀请，看了[Zotero Better Notes](https://github.com/windingwind/zotero-better-notes)插件，做得非常好，也非常专业，之前跟小伙伴聊天时也提及过该插件，口碑很不错。
请问现在有什么想法，我能做些什么？

**Comment by windingwind** [comment]
您好，
感谢您的热心回复。首先向您介绍Better Notes(下称BN)的主要功能：通过引入笔记链接，可在阅读文献时从批注等处快速创建并插入链接到特定的主笔记中。在主笔记中整理、组织所有笔记链接，形成知识大纲。大纲可在导出时嵌入所有链接的子笔记。

最近（开发插件后）了解了卡片笔记法，有一句印象深刻：写作之难，在于把网状的思考，用树状的语法结构，转换成线性字符串（亦即论文等产出）。从这个观点来看，BN所做的正是从网状知识卡片到树状知识大纲（主笔记），再导出为线性字符串的过程。

恰好您的插件（zotcard，zotdraw）专门针对卡片本身做了很多的支持，并在图形化方面探索得更远。这可以很好地与BN的文本化卡片相结合。

以上是合作基础及开发理念角度的一些想法。关于合作，目前设想的主要交集点是：
1. 将BN中主笔记中的所有链接子笔记以卡片形式展示；
2. 从归类的卡片/绘图导入主笔记
3. BN实现的笔记链接可以作为笔记方面的一项基础服务，融合到zotdraw的体系中去，可从zotero外通过链接打开笔记。

设想的笔记生态图：
![114ae0068b57375388654be2703021d](https://user-images.githubusercontent.com/33902321/169842469-23ff03d4-170c-47cf-b8fb-99d0319d2f5a.jpg)

以上是我的一些想法，供您参考。

祝好！

**Comment by 018** [comment]
zotdraw往后的功能定位尚未清晰，待我梳理之后再看情况。感谢。
