### ISSUE TITLE
请问在建立卡片模板的时候选择插入字段的时候能否插入论文标签

### ISSUE THREAD

**Issue by nickcao123456** [018/zotcard#21]
您好！请问在建立卡片模板的时候选择插入字段的时候能否插入论文标签，这样子在zotero better notes的工作区里面更加方便管理和筛选，期待您跟zotero better notes作者的合作！

**Comment by 018** [comment]
论文标签？截图看看。
zotero better notes是个优秀的插件，迭代速度让人佩服，我跟不上。😂

**Comment by nickcao123456** [comment]
![屏幕截图 2023-02-02 132956](https://user-images.githubusercontent.com/79524971/216240117-a1efc6ec-033d-46e8-97d9-bf3d0e11d53f.png)

**Comment by nickcao123456** [comment]
![屏幕截图 2023-02-02 133340](https://user-images.githubusercontent.com/79524971/216240423-4698b9d8-78d1-4ca5-8df7-5190c2777fee.png)

**Comment by nickcao123456** [comment]
好的，谢谢作者！

**Comment by 018** [comment]
已经发布了。
