### ISSUE TITLE
卡片导出pdf的页面距现在是0，请问怎么增加页面距呀？

### ISSUE THREAD

**Issue by FemiSphere** [018/zotcard#23]
急求

**Comment by 018** [comment]
打印出来的pdf吗？

**Comment by FemiSphere** [comment]
【您好，马心远已经收到信息，感谢您百忙之中垂询】Hello,mxy have received information。Thank you for your busy schedule Inquiries

**Comment by FemiSphere** [comment]
是的，就是通过zotcard读卡页面导出来的pdf页边距是0，不太方便打印和传阅。
我看到您github上发布的最新一版里面专门提到说打印页边距为0这个特性，想问问怎么修改呀？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月2日(周四) 上午10:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [018/zotcard] 卡片导出pdf的页面距现在是0，请问怎么增加页面距呀？ (Issue #23)




 
打印出来的pdf吗？

**Comment by 018** [comment]
收到，我会在最新版本里添加「页面边距」选项，不日发布。

**Comment by FemiSphere** [comment]
收到，非常感谢您！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月2日(周四) 下午3:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [018/zotcard] 卡片导出pdf的页面距现在是0，请问怎么增加页面距呀？ (Issue #23)




 
收到，我会在最新版本里添加「页面边距」选项，不日发布。

**Comment by ZHAO0514** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你好 请问如何取消对我的抄送呀~
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1107001425
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年02月2日 15:59
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [018/zotcard] 卡片导出pdf的页面距现在是0，请问怎么增加页面距呀？ (Issue #23)
        
      
    
  
  

收到，非常感谢您！















---原始邮件---



发件人: ***@***.***&gt;



发送时间: 2023年2月2日(周四) 下午3:57



收件人: ***@***.***&gt;;



抄送: ***@***.******@***.***&gt;;



主题: Re: [018/zotcard] 卡片导出pdf的页面距现在是0，请问怎么增加页面距呀？ (Issue #23)



















 



收到，我会在最新版本里添加「页面边距」选项，不日发布。



 



—



Reply to this email directly, view it on GitHub, or unsubscribe.



You are receiving this because you authored the thread.Message ID: ***@***.***&gt;



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by FemiSphere** [comment]
> 

不好意思哈，我也没注意到抄送到您哪里了，邮件是github自动转发的

**Comment by ZHAO0514** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    搜嘎 好嘞 没关系，我摸索一下看如何取消~
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1107001425
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年02月2日 16:31
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [018/zotcard] 卡片导出pdf的页面距现在是0，请问怎么增加页面距呀？ (Issue #23)
        
      
    
  
  





不好意思哈，我也没注意到抄送到您哪里了，邮件是github自动转发的



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by 018** [comment]
已经发布了。
