### ISSUE TITLE
添加 publication 字段

### ISSUE THREAD

**Issue by dawnlh** [018/zotcard#7]
你好~ 请问能不能将 zotero 条目中的 publication字段信息 添加在zotcard，类似于 {authors} 的这种。因为现有的 publisher 字段往往是出版社名字，不是期刊名字，不是很方便。谢谢

**Comment by 018** [comment]
应该是publicationTitle，在新版本会加上。

**Comment by dawnlh** [comment]
期待，感谢！ 👍
