### ISSUE TITLE
在“读卡”窗口，添加“合并导出”，“打印”功能

### ISSUE THREAD

**Issue by zyx335588** [018/zotcard#8]
希望能在`读卡`窗口添加以下功能：
1. **合并导出**：将筛选出的笔记合并，导出到一个HTML文件或者PDF文件。这样可以利用`读卡`原本的`按照标签筛选`、`按照日期筛选`以及`搜索`功能，将某一主题的笔记进行整合到一个文件进行汇总。
2. “打印”：作为 **1** 的一个补充吧。

**Comment by 018** [comment]
1、可以考虑导出html文件。
2、目前只能支持一卡一卡的打印。

**Comment by 018** [comment]
新版本已经支持导出html。 https://github.com/018/zotcard/releases/tag/v2.4
